#!/bin/bash

# Download random image
curl -L -o /tmp/youvebeenbiebered.jpg https://bieber.party/today

# Apply background
osascript -e 'tell application "System Events" to set picture of every desktop to "/tmp/youvebeenbiebered.jpg"'
